# Site settings
title: Video To GIF Converter
description: A modern, browser-based tool for converting video clips to GIF animations
url: https://dylansallred.github.io/

# Theme settings
theme: jekyll-theme-minimal
google_analytics: # Add your Google Analytics ID here if needed

# Build settings
markdown: kramdown 